@startmindmap

<style>
mindmapDiagram{
	.blue {
		BackgroundColor LightBlue
	}
}
</style>


* Einschränkungen <<blue>>
	* Körperliche Einschränkungen
		* Sinne
		* Herzkreislauf und Stoffwechsel
		* Atmung
		* Verdauungssystem
		* Endokrinologie
		* Schmerzen und chronische Belastbarkeit
		* Onkologische Folgen
		* Temperatur- und Umweltregulation
		* Autonome Funktionen
		* Gehvermögen
		* Sprechvermogen
		* Fein- und grobmotorische Einschränkungen
		* Haut und Immunsystem
@enduml