@startgantt Zeitplan Masterarbeit
' SETUP
printscale weekly
today is colored in red
Project starts 2025-12-06

'footer Printdate: %date("YYYY-MM-dd") (red line)
 
' HOLIDAYS
'2025-11-25 to 2025-12-07 are named [Ferien]
'2025-11-25 to 2025-12-07 are colored in salmon

2026-02-01 to 2026-02-07 are named [Skilager]
2026-02-01 to 2026-02-07 are colored in salmon
'2026-02-01 to 2026-02-07 is closed 

-- Körperliche Einschränkungen finden --
[Literaturrecherche] requires 5 days
[Arten von Einschränkungen recherchieren] starts at [Literaturrecherche]'s end and requires 5 days
[M1: Arten von Einschränkungen recherchiert ] happens at [Arten von Einschränkungen recherchieren]'s end

-- Auf die häufigsten reduzieren --
[Häufigste Einschränkungen ermitteln] starts at [Arten von Einschränkungen recherchieren]'s end and requires 5 days
[Auf die häufigsten Einschränkungen reduziert] starts at [Häufigste Einschränkungen ermitteln]'s end and requires 5 days

[M2: Relevante Einschränkungen gefiltert ] happens at [Auf die häufigsten Einschränkungen reduziert]'s end

-- Parameter und VR-Simulationsmöglichkeiten finden --
[Parameter der Einschränkungen sammeln] starts at [Auf die häufigsten Einschränkungen reduziert]'s end and requires 5 days
[Erstgespräch mit Fachexperten oder Betroffenen] starts at [Auf die häufigsten Einschränkungen reduziert]'s end and requires 10 days and is colored in orange
[Simulationsmethoden entwickeln] starts at [Auf die häufigsten Einschränkungen reduziert]'s end and requires 15 days
[M3: Parameter und VR-Simulationsmethoden gefunden ] happens at [Simulationsmethoden entwickeln]'s end


-- Validierung --

[Simulationsmethoden mit Experten/Betroffenen validieren] starts at [Simulationsmethoden entwickeln]'s end and requires 5 days and is colored in orange
[M4: Simulationsmethoden validieren ] happens at [Simulationsmethoden mit Experten/Betroffenen validieren]'s end


-- Bericht --
[Bericht schreiben] starts at [Simulationsmethoden mit Experten/Betroffenen validieren]'s end and requires 10 days
then [Berichtskorrektur] starts at 2026-02-01 and ends at 2026-02-07 and is colored in Green

then [Bericht finalisieren / Reserve] starts at 2026-02-08 and requires 13 days

-- Abgabe --
[Abstract] starts at [Bericht finalisieren / Reserve]'s end and requires 6 days
[Berichtabgabe] starts at [Abstract]'s end and requires 1 days
[M5: Masterarbeit abgegeben] happens 2026-02-27




legend
Legende:
|= Farbe  |= Beschreibung              |
|<#orange>| Abhängig von Fremdpersonen |
|<#green> | Fremdleistung              |
|<#salmon>| Ferien                     |
end legend

@endgantt